CREATE TABLE Salas (
    ID SERIAL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Andar INTEGER NOT NULL,
    QuantidadeAssentos INTEGER NOT NULL
);

CREATE TABLE Reservas (
    ID SERIAL PRIMARY KEY,
    SalaID INTEGER NOT NULL REFERENCES Salas(ID) ON DELETE CASCADE,
    Inicio TIMESTAMPTZ NOT NULL,
    Fim TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_sala_inicio UNIQUE (SalaID, Inicio)
);